### ISSUE TITLE
Tagalog Translation Progress

### ISSUE THREAD

**Issue by tesseralis** [reactjs/tl.reactjs.org#1]
## Maintainer List

* @elrmndo 
* @lacson17

## Join our discord server (FYI this link has a limit of 5 uses)
https://discord.gg/7g3fbtM

## For New Translators

To translate a page:

1. Check that no one else has claimed your page in the checklist and comments below. As of Oct 2020, we're using this board https://github.com/reactjs/tl.reactjs.org/projects/1, pls have a look on the `TO DO` list. You'll see them as assigned but anyone can still ask to work on something as long as it's in `TO DO`. We just pre-assigned it to people for them to work on something immediately when our task is done and to avoid more than one person working on the same task.
2. Comment below with the name of the page you would like to translate. **Please take only one page at a time**.
3. Clone this repo, translate your page, and submit a pull request!

Before contributing, read the glossary and style guide (once they exist) to understand how to translate various technical and React-specific terms.

Please be prompt with your translations! If you find that you can't commit anymore, let the maintainers know so they can assign the page to someone else.

## For Maintainers

When someone volunteers, edit this issue with the username of the volunteer, and with the PR. Ex:

* [ ] Home Page (@tesseralis) #1

When PRs are merged, make sure to mark that page as completed!

## Core Pages

To do before releasing as an "official" translation. **Please translate these pages first.**

* [ ] Home Page (@elrmndo)
* [ ] Tutorial

### Basics

* [x] Hello World (@jorenrui) #2 
* [x] Introducing JSX (@TheoryOfNekomata) #7
* [ ] Rendering Elements
* [ ] Components and Props
* [ ] State and Lifecycle (@warrenca) #35 
* [x] Handling Events (@theAspiringDev1) #34
* [ ] Conditional Rendering
* [x] Lists and Keys (@warrenca) #20
* [x] Forms (@jorenrui) #11
* [ ] Lifting State Up (@TheoryOfNekomata)
* [ ] Composition vs Inheritance
* [x] Thinking in React (@warrenca) #19

### API Reference

* [ ] React
* [ ] React.Component
* [ ] ReactDOM
* [ ] ReactDOMServer
* [ ] DOM Elements
* [ ] SyntheticEvent
* [ ] Test Utilities
* [ ] Shallow Renderer
* [ ] Test Renderer
* [ ] JS Environment Requirements
* [ ] Glossary

### Navigation

These are the navigation links that appear in the sidebar. Possibly wait until
the corresponding sections are translated to do these.

* [ ] tutorial/nav.yml
* [ ] docs/nav.yml

## Next Steps

These are the next most important translations, ordered by importance:

### Installation

* [ ] Getting Started
* [ ] Add React to a Website
* [ ] Create a New React App
* [ ] CDN Links

### Hooks

Everyone is hooked on hooks! People are really excited about these and it would be great for them to be translated.

  * [ ] Introducing Hooks
  * [ ] Hooks at a Glance
  * [ ] Using the State Hook
  * [ ] Using the Effect Hook
  * [ ] Rules of Hooks
  * [ ] Building Your Own Hooks
  * [ ] Hooks API Reference
  * [ ] Hooks FAQ

### Warnings

These are the pages that you get when you click the links in the console (e.g. https://reactjs.org/warnings/dont-call-proptypes.html). People tend to search these, so **please don't translate the error message itself**.
 
* [ ] dont-call-proptypes
* [ ] invalid-aria-prop
* [ ] invalid-hook-call-warning
* [ ] legacy-factories
* [ ] refs-must-have-owner
* [ ] special-props
* [ ] unknown-prop

### Advanced Guides

* [ ] Accessibility
* [ ] Code-Splitting
* [ ] Context
* [ ] Error Boundaries
* [ ] Forwarding Refs
* [ ] Fragments
* [ ] Higher-Order Components
* [ ] Integrating with Other Libraries
* [ ] JSX In Depth
* [ ] Optimizing Performance
* [ ] Portals
* [ ] React Without ES6
* [ ] React Without JSX
* [ ] Reconciliation
* [ ] Refs and the DOM
* [ ] Render Props
* [ ] Static Type Checking
* [ ] Strict Mode
* [ ] Typechecking With PropTypes
* [ ] Uncontrolled Components
* [ ] Web Components

### FAQ

* [ ] APIs and AJAX
* [ ] Babel, JSX, and Build Steps
* [ ] Passing Functions to Components
* [ ] Component State
* [ ] Styling and CSS
* [ ] File Structure
* [ ] Versioning Policy
* [ ] Virtual DOM and Internals

### Contributing

Priority: Low

* [ ] How to Contribute
* [ ] Codebase Overview
* [ ] Implementation Notes
* [ ] Design Principles

### Components

Components in `src/components` that have some text in them.

* [ ] CodeEditor
* [ ] CodeExample
* [ ] ErrorDecoder
* [ ] LayoutFooter
* [ ] LayoutHeader
* [ ] MarkdownPage

## Additional Translations

These are not the primary translation targets.

* [ ] Blog
* [ ] Community

**Comment by elrimando** [comment]
@lacson17 i'll start with the homepage.

**Comment by BosEriko** [comment]
Hey, @elrmndo and @tesseralis! Are you guys still doing this? Or is this translation dropped?

**Comment by elrmndo** [comment]
Hi @BosEriko, this translation is not dropped, we're actually looking for other contributors to continue.

**Comment by BosEriko** [comment]
@elrmndo awesome! Tagging in @jorenrui because we've been looking at this issue for a while now. Glad to hear it's still ongoing!

**Comment by jorenrui** [comment]
@elrmndo Yesh~ Would love to help out! Also if ever there's a Discord Channel for Filipino devs, can we join? 👀

**Comment by elrmndo** [comment]
Cool, hang on and I will be submitting a PR in order for you guys to be added as a maintainer.

@jorenrui not sure about a Discord Channel/Server for Filipino Devs tho, that would be cool tho if we could join one

**Comment by jorenrui** [comment]
Ow I see. Can I start with [Basics: Hello World](https://reactjs.org/docs/hello-world.html)? Wanted to start with something small first 😁 Also a style guide would be nice

**Comment by TheoryOfNekomata** [comment]
How do you communicate with the translation tasks tho?

**Comment by elrmndo** [comment]
@jorenrui great, i'll tag you in the post. we'll work on that as soon as possible, if you have suggestions feel free 🙂

Hi, @TheoryOfNekomata! As of now we don't have any other communication channel other than here. That's great try picking up one page then let's move on from that 🙂

**Comment by warrenca** [comment]
> Cool, @jorenrui not sure about a Discord Channel/Server for Filipino Devs tho, that would be cool tho if we could join one
> 
> Edit: feel free to pick a page that you want to translate then coment it here, also, we will be coming up with a style guide along the way to assist us in the translation, have great day! 🤟

@elrmndo If you or others here are keen, I've setup a discord server https://discord.gg/6QP4uzt, anyone can join for now. I'm new to discord, I can share the admin role to someone who knows it better. Also, I'm totally new to translation but I really want learn it.

**Comment by jorenrui** [comment]
@elrmndo Okie. Thanks 😁

That's great @warrenca ! I've joined the server. @TheoryOfNekomata and @BosEriko can join to an we can talk there 👀

**Comment by warrenca** [comment]
@elrmndo Can we have a Kanban board here in the github project so we can easily track who's doing what and what's the progress?

**Comment by warrenca** [comment]
Hi @elrmndo, thanks for creating the Kanban board. If you don't mind. I will create the issues and put them in the board and assign them to people. But you have to give me rights for that as I can't add issues to the board and can't assign issues to people either. Thanks again.

Also, if you have time to join the discord https://discord.gg/6QP4uzt, that would be great as well.

**Comment by elrmndo** [comment]
Hi @warrenca, please check your access if you are able to do such also I have joined the discord server.

**Comment by warrenca** [comment]
Thank @elrmndo

**Comment by elrmndo** [comment]
Picking up the homepage.

**Comment by TheoryOfNekomata** [comment]
Please assign _Introducing JSX_ to me @elrmndo. Thanks!

**Comment by theAspiringDev1** [comment]
Hello , I want to contribute in the translation . Can I translate the Handling Events page ?

**Comment by warrenca** [comment]
@theAspiringDev1 sure, I'm assigning that to you. Also, have a look at this board https://github.com/reactjs/tl.reactjs.org/projects/1

**Comment by gaearon** [comment]
It looks like this translation has stalled, and is now very outdated.
I'm going to archive this repo, but if someone wants to pick up, please start a new effort.
